defaults:
  # [핵심 수정] api/파일이름@저장위치 형식으로 변경하여 충돌 방지
  - api/polygon@api.polygon
  - api/fmp@api.fmp
  - api/ollama@api.ollama
  
  # 나머지는 그대로
  - database: duckdb
  - settings: logging
  - _self_

project_name: "quant-agent-v2"

# 분석 대상 종목 리스트
symbols: ["GOOGL", "AAPL", "META", "TSLA"]

# 데이터 수집 기간
date_range:
  start: "2024-12-02"
  end: "2025-12-02"